name: "Validate Gradle Wrapper"
on:
  pull_request:
    paths:
      - 'gradle/wrapper/**'
  push:
    paths:
      - 'gradle/wrapper/**'

jobs:
  validation:
    name: "Validate Wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
